### ISSUE TITLE
script can't handle multiple taxon IDs

### ISSUE THREAD

**Issue by morien** [naturalis/Simple-LCA#2]
in current blast fmt 6 output, some hits have multiple taxonIDs with a ";" delimiter. your script throws a key error when it tries to process these hits. example output:

```
  File "Simple-LCA/add_taxonomy.py", line 78, in <module>
    main()
  File "Simple-LCA/add_taxonomy.py", line 74, in main
    add_taxonomy(taxonomyDict, mergedTaxonDict)
  File "Simple-LCA/add_taxonomy.py", line 61, in add_taxonomy
    kingdom = taxonomydb[taxid]["kingdom"]
KeyError: '77133;212695'
```

i spot checked a couple of these, i believe taking the last taxonID in the sequence could be an adequate fix. the ones i checked were most informative at the end of the chain.

**Comment by gbbio** [comment]
Hello morien,

This repository started as sort of a test script and is not maintained anymore.
Look at this repository for the elaborated LCA analyses script and method:
https://github.com/naturalis/galaxy-tool-lca

Therefore the above script is designed to fit specifically in the Naturalis infrastructure, but if you want to use it yourself you also need to take a look at this repo:
https://github.com/naturalis/galaxy-tool-BLAST

For the issue that you specifically pointed out, instead of changing the script you could blast with the parameter ```6 qseqid stitle sacc staxid pident qcovs evalue bitscore``` instead of ```6 qseqid stitle sacc staxids pident qcovs evalue bitscore``` the difference is the ```staxid``` part. But then again, you should not use this script and I highly recommend you to look at those other repositories and not at this one.

**Comment by morien** [comment]
hi and thanks for quickly replying, i didn't realize the repo was not maintained. i'd seen the galaxy tools before, but since i don't use galaxy, i avoided them. thanks for clarifying, i can see now you can use these tools without using galaxy, so i will give them a try.

FYI, however, my blast command already includes this:
`-outfmt '6 qseqid stitle sacc staxids pident qcovs evalue bitscore'`
and still produces the semicolon-delimited taxIDs in the staxid column.

**Comment by gbbio** [comment]
Galaxy can be seen as just a wrapper or UI build around the commandline. 

Yes I see your command but look closely to my first command. You have the word ```staxids``` in plural. And to not need to change the script you could use ```staxid```. 

But I would not know if you need to tweek the script on other parts. Ncbi moved the blast database v5 and when this was used for a test it was v4.

**Comment by morien** [comment]
oh gosh, sorry, i didn't catch that there were plural and singular versions of the staxid parameter. thanks for clarifying.
